spring.application.name=githubpranalyzer

logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mongodb.uri=mongodb://root:root@localhost:27017/pr_analyzer?authSource=admin