spring.application.name=githubpranalyzer

logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mongodb.uri=mongodb://root:root@${MONGODB_HOST:localhost}:27017/pr_analyzer?authSource=admin

github.webhook.secret=${GITHUB_WEBHOOK_SECRET:meu-secret-local}

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000