spring.application.name=githubpranalyzer

logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
de.flapdoodle.mongodb.embedded.version=7.0.0
spring.rabbitmq.listener.simple.auto-startup=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mongodb.uri=mongodb://root:root@localhost:27017/pr_analyzer?authSource=admin

github.webhook.secret=${GITHUB_WEBHOOK_SECRET:meu-secret-local}